### ISSUE TITLE
Resolve CORS issue on vercel hosted app

### ISSUE THREAD

**Issue by shelcia** [shelcia/mocker#10]

**Comment by Sparsh752** [comment]
@shelcia can you describe the issue a bit more

**Comment by shelcia** [comment]
This may need Backend work, usually on vercel hosted app there will be CORS error when using endpoints produced in the tool

**Comment by Sparsh752** [comment]
@

> This may need Backend work, usually on vercel hosted app there will be CORS error when using endpoints produced in the tool

@shelcia Then you may assign someone else then

**Comment by Sparsh752** [comment]
@shelcia I saw on the internet that putting 
  "headers": [
    {
      "source": "/api/(.*)",
      "headers": [
        { "key": "Access-Control-Allow-Credentials", "value": "true" },
        { "key": "Access-Control-Allow-Origin", "value": "*" },
        { "key": "Access-Control-Allow-Methods", "value": "GET,OPTIONS,PATCH,DELETE,POST,PUT" },
        { "key": "Access-Control-Allow-Headers", "value": "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version" }
      ]
    }
  ]
in vercel.json will resolve CORS issue. Is that right?

**Comment by Sparsh752** [comment]
@shelcia But you have tagged this hard, it must be something difficult

**Comment by Sparsh752** [comment]
@shelcia How do I check whether it is working or not

**Comment by shelcia** [comment]
deployment failed
