### ISSUE TITLE
Add code-of-conduct and CONTRIBUTING

### ISSUE THREAD

**Issue by shelcia** [shelcia/mocker#114]

**Comment by nerdy-nakul** [comment]
Hello @shelcia,
I'm working on this issue please assign me this issue.
Also please send your mail so that i can add it to CODE_OF_CONDUCT.md

**Comment by nerdy-nakul** [comment]
Hello @shelcia,
I have made a PR adding CODE_OF_CONDUCT.md & CONTRIBUTING.md
You may check.
