### ISSUE TITLE
email verification

### ISSUE THREAD

**Issue by shelcia** [shelcia/mocker#12]

**Comment by sidling1** [comment]
can you assign this to me?

**Comment by MCoder86A** [comment]
@sidling1 Are you working on it?

**Comment by MCoder86A** [comment]
>An error occurred with your deployment
FUNCTION_INVOCATION_TIMEOUT

@shelcia `api/service/verify_email` endpoint giving TIMEOUT error. The endpoint is responsible to send email. Can you confirm if you set the environment variable before deployment ?

![Screenshot (33)](https://user-images.githubusercontent.com/56883128/207803487-fea80b68-ad3c-4975-a691-f3f28fce6bf7.png)

**Comment by MCoder86A** [comment]
[EMAIL_VERIFY_MOCKER.webm](https://user-images.githubusercontent.com/56883128/207820575-24bbfad1-fdc6-46a1-aec5-cdd9ef2c8a9d.webm)

@shelcia So I have deployed the backend and its working.. Can you redeploy the backend after setting the .env variable [.env](https://github.com/shelcia/mocker/pull/44/commits/6d71494b1f1c7aeb65e9915290c3399ca6e82ab7#diff-0e320819a20d54d985ec682f82c0e0be462b12a8a26e57a339cb68947fcfeeb6R5-R6)

**Comment by shelcia** [comment]
Which email provider you are using @MCoder86A ?

**Comment by MCoder86A** [comment]
@shelcia I am using gmail

**Comment by MCoder86A** [comment]
I have generate the password as shown [here](https://medium.com/@TusharKanjariya/send-email-using-node-mailer-in-node-js-b813734e9a3e)

**Comment by MCoder86A** [comment]
@shelcia I am unaware of importance of codepeak22 label.. now I got to know about it. Can you please add codepeak22 label in this issue
