### ISSUE TITLE
[DOC] Update README File

### ISSUE THREAD

**Issue by Suryansh1720001** [shelcia/mocker#127]
Hello @shelcia 

### Features that I want to add in README File

- Contributors details
- Project admin details
- Add the contributing line with a guideline link so that everyone motivates by that.
- Center heading for more attractive
- adding the footer part in the readme file

*Describe the solution you'd like*

- Add new features

Kindly assign this issue to me under IWOC event with the label of medium.

**Comment by RyanWalker277** [comment]
Dont raise these kind of issues on any project.If you want to raise any issue, better find a bug or enhancement to work upon. Close all such issues which you have created. There are 8 in total, kindly close all of them.

**Comment by Suryansh1720001** [comment]
@RyanWalker277 
Although I am aware of that, my focus is on working with Kotlin android projects, and currently, there is only one project available under IWOC. That's why I raised this issue. Among the listed Kotlin project, I regularly work on fixing bugs and implementing new features. If you take a look at my profile, you can see this for yourself. It's true that maybe I have raised some issues related to the readme files, but that was only for the IWOC. Since, as I mentioned earlier, there is only one Kotlin project available. 
Nevertheless, I won't be raising such issues in the future.

**Comment by Suryansh1720001** [comment]
#129 Check and merge this accordingly
