### ISSUE TITLE
hide/show password

### ISSUE THREAD

**Issue by shelcia** [shelcia/mocker#13]

**Comment by iamatifmoin** [comment]
@shelcia 
Can you assign me this issue?

**Comment by himanshu1221** [comment]
can you assign this issue to me under KWoC22

**Comment by iamatifmoin** [comment]
@shelcia 
I have made the suggested changes in this new PR.

**Comment by MaYaNkKashyap681** [comment]
Is this issue still open? If yes then can i work on this.
