### ISSUE TITLE
Group Fields in adding resource dropdown

### ISSUE THREAD

**Issue by shelcia** [shelcia/mocker#23]
Tech ref: https://mui.com/material-ui/react-select/#grouping

Grouping ref: https://fakerjs.dev/api/

![Screenshot 2022-12-06 at 3 33 56 AM](https://user-images.githubusercontent.com/31156685/205752163-fce83d29-b82a-43f0-94cf-910123f7fdc2.png)

**Comment by shelcia** [comment]
```
     <FormControl sx={{ m: 1, minWidth: 120 }}>
        <InputLabel htmlFor="grouped-select">Grouping</InputLabel>
        <Select defaultValue="" id="grouped-select" label="Grouping">
          <MenuItem value="">
            <em>None</em>
          </MenuItem>
          <ListSubheader>Category 1</ListSubheader>
          <MenuItem value={1}>Option 1</MenuItem>
          <MenuItem value={2}>Option 2</MenuItem>
          <ListSubheader>Category 2</ListSubheader>
          <MenuItem value={3}>Option 3</MenuItem>
          <MenuItem value={4}>Option 4</MenuItem>
        </Select>
      </FormControl>
```

**Comment by AbhiPatel10** [comment]
Need more clarification on this issue.

**Comment by shelcia** [comment]
There is a way to group the fields through MUI https://mui.com/material-ui/react-select/#grouping

The grouping needs to be done based on https://fakerjs.dev/api/. (category wise)

**Comment by AbhiPatel10** [comment]
Go for it, @shelcia Please assign this issue to @abdullahranginwala

**Comment by MCoder86A** [comment]
@shelcia Can you add codepeak22 label in this issue
