### ISSUE TITLE
Login and SignUp Box Size Change when Error Occurs in Password input.

### ISSUE THREAD

**Issue by AbhiPatel10** [shelcia/mocker#47]
When error occurs in password input like "Password should be of minimum 6 characters length" then  Login and Sign Up form size is increase.

solution :- size of box should not change

### Before Error

![image](https://user-images.githubusercontent.com/76242769/207811726-80b018eb-644a-41d5-b22c-790cebe87109.png)

### After Error

![image](https://user-images.githubusercontent.com/76242769/207811881-0ed5c129-62a9-4180-836f-0c6c3ccc434f.png)

Please assign this issue to me and add coadpeack22 label on it.

**Comment by shelcia** [comment]
Yes I want to fix it as well, but I hoped when someone worked on homepage enhancement, it will be fixed with that. You can work on this as of now though.
