### ISSUE TITLE
Option menu should retain its previous data

### ISSUE THREAD

**Issue by MCoder86A** [shelcia/mocker#63]
When editing or cloning, the option data does not retain its previous value if any.
![image](https://user-images.githubusercontent.com/56883128/208581256-759a3a49-3c05-4b49-b65d-76b020c12642.png)

I shall fix this issue. please assign me

**Comment by shelcia** [comment]
the data is uncontrolled. It was your code only .

**Comment by MCoder86A** [comment]
@shelcia Can you please elaborate more on the issue you are facing like resulting in unexpected result or something.. The issue I am thinking to fix is to get the previous data while cloning or editing. If there is any other issue I would be happy to fix it.

**Comment by shelcia** [comment]
![Screenshot 2022-12-21 at 12 21 13 AM](https://user-images.githubusercontent.com/31156685/208743785-9e6f22d8-da04-4e64-9ccd-6aeaa9d25c58.png)

the data is uncontrolled
