### ISSUE TITLE
Add options for date with schema options

### ISSUE THREAD

**Issue by shelcia** [shelcia/mocker#70]
[between](https://fakerjs.dev/api/date.html#between)
[betweens](https://fakerjs.dev/api/date.html#betweens)
[birthdate](https://fakerjs.dev/api/date.html#birthdate)
[future](https://fakerjs.dev/api/date.html#future)
[month](https://fakerjs.dev/api/date.html#month)
[past](https://fakerjs.dev/api/date.html#past)
[recent](https://fakerjs.dev/api/date.html#recent)
[soon](https://fakerjs.dev/api/date.html#soon)
[weekday](https://fakerjs.dev/api/date.html#weekday)

**Comment by MCoder86A** [comment]
Please assign me
