### ISSUE TITLE
Add option for datatype with schema options

### ISSUE THREAD

**Issue by shelcia** [shelcia/mocker#71]
[array](https://fakerjs.dev/api/datatype.html#array)
[bigInt](https://fakerjs.dev/api/datatype.html#bigint)
[boolean](https://fakerjs.dev/api/datatype.html#boolean)
[datetime](https://fakerjs.dev/api/datatype.html#datetime)
[float](https://fakerjs.dev/api/datatype.html#float)
[hexadecimal](https://fakerjs.dev/api/datatype.html#hexadecimal)
[json](https://fakerjs.dev/api/datatype.html#json)
[number](https://fakerjs.dev/api/datatype.html#number)
[string](https://fakerjs.dev/api/datatype.html#string)
[uuid](https://fakerjs.dev/api/datatype.html#uuid)

**Comment by MCoder86A** [comment]
Please assign me

**Comment by MCoder86A** [comment]
@shelcia PR #68 which was merged but not visible in last commit of master branch. So can I pause working in this issue until changes made into #68 is visible in last commit of master branch to avoid conflicts in future. Same with issue #70

**Comment by shelcia** [comment]
it is merged

**Comment by MCoder86A** [comment]
Yes it is visible now. Thanks. There are some other PR also with same issue.. #61 and #67 merged but not visible.
