### ISSUE TITLE
Fix code scanning alert - Database query built from user-controlled sources

### ISSUE THREAD

**Issue by shelcia** [shelcia/mocker#74]
Tracking issue for:
- [ ] https://github.com/shelcia/mocker/security/code-scanning/1

**Comment by MCoder86A** [comment]
The link is not working. It shows 404 page not found.
Do you mean error in codeql code scanning after PR raise? But I couldn't see any error after I raised a PR. Can you elaborate more on the issue?
![image](https://user-images.githubusercontent.com/56883128/209553353-f3817dda-c55a-4aa4-b642-01bd38bd51fa.png)

**Comment by shelcia** [comment]
![Screenshot 2022-12-27 at 11 57 49 PM](https://user-images.githubusercontent.com/31156685/209707727-73dc8db8-1e6e-4569-9185-40addd7ce28e.png)

**Comment by MCoder86A** [comment]
I got it now.. I have worked with mysql query sanitization so I will try with mongodb query sanitization.. please assign this to me
