### ISSUE TITLE
[Feature]: Adding Copy API url function

### ISSUE THREAD

**Issue by shelcia** [shelcia/mocker#98]
![Screenshot 2023-01-03 at 12 47 45 AM](https://user-images.githubusercontent.com/31156685/210271213-77777edf-3861-4934-bbb7-3cc580f58c61.png)

**Comment by MCoder86A** [comment]
Did not understand which url to copy. Can you give an example? or do you want to copy `https://mocker-backend.vercel.app/api/user/:endpoint` ?

**Comment by shelcia** [comment]
yes
